### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by shreelock**
Updating the README for unmounting, as per #31

### CODE REVIEW

**Comment by wshayes** [comment]
Might be helpful to state that it doesn't show up as a normal mounted drive in Finder - you have to navigate to the mounted directory location in order to be able to eject it.  Maybe there is a Finder preference to get it to show up on the left sidepane to more easily eject it, but mine isn't setup that way.

BTW - This is an awesome project! Thanks!

**Comment by mischievous** [comment]
Not showing up in finder has been fixed for a LONG time.  You have to add "-olocal" to the sshfs options.  As a stupid side note my rewrite of MacFushion (https://github.com/mischievous/macfusion3) has this option available, but I might need to update the GitHub project with my latest code not sure.

**Comment by wshayes** [comment]
Didn't mean to say it's not showing up - it is. I was looking for it in the mounted drives in the Finder sidebar instead of in the file/directory listing in the listing section of Finder.

**Comment by mischievous** [comment]
Yes, I understood.   Try the “-olocal” option.   It works great for me and shows up under devices.  I can take a screen shot if you dont belive me.   Oh!   Are you not mountaing unders /Volumes?

**Comment by wshayes** [comment]
Ah - now I understand - I test mounted in a subfolder of a project - worked great!  I'll try the -olocal and in the /Volumes dir - so probably does make sense to detail a bit more in the Readme for this as my assumptions were off :)

**Comment by bfleischer** [comment]
macOS specific changes have been merged into the upstream project at https://github.com/libfuse/sshfs. Future development will continue there.

**Pull request closed without merging**
