### PR TITLE
Cache options

### PR DESCRIPTION
**Pull request by jmmv**
Adds the ability to configure the cache size and behavior from command-line options and clarifies the code a tiny little bit.

### CODE REVIEW

**Comment by jmmv** [comment]
@bfleischer From what I can tell, you may be the only one around to take a look and I'm not sure you have seen this. Could you? Thanks!

**Comment by bfleischer** [comment]
Sorry @jmmv, for the late reply. I've been busy the past few days.

Your changes do not seem to be OS X specific. I think it might be best to apply them to the upstream (Linux) SSHFS repository https://github.com/libfuse/sshfs and then merge them back into this repository. This way we can keep the differences between Linux SSHFS and OS X SSHFS to a minimum.

@Nikratio What do you think?

**Comment by jmmv** [comment]
That sounds fine to me, though somehow I didn't get the impression that osxfuse-sshfs was tracking the Linux sshfs. I can rebase them against the Linux implementation if you'd like.

**Comment by Nikratio** [comment]
I'd be happy to consider them.

I did not know that osxfuse-ssh was tracking sshfs either. Has there ever been an attempt to simply merge the OS-X specific changes into sshfs? From what I have seen in my work on python-llfuse, the FUSE and OSXFUSE API is almost identical, so there shouldn't be that many differences.

**Comment by jmmv** [comment]
@Nikratio That's correct: the differences between the two sshfs copies are minimal. I did a `diff -ru` on the two source trees before submitting this PR and found that the changes are quite simple and already protected behind compiler conditionals. The reason I concluded that osxfuse's copy did not track the Linux one was because I did not see any indication of such in the commit history.

Merging the two copies would be a nice result, I'd say.

**Comment by jmmv** [comment]
osxfuse's sshfs has been merged into libfuse's master copy and I have rebased this PR onto that one as https://github.com/libfuse/sshfs/pull/6

**Pull request closed without merging**
